# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather_data.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 34, 1, "", "weather_data.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12weather_data.proto\x12\x0cweather_data"\x9c\x02\n\x0fWeatherDataFull\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x10\n\x08pressure\x18\x04 \x01(\x02\x12\x12\n\nwind_speed\x18\x05 \x01(\x02\x12\x16\n\x0ewind_direction\x18\x06 \x01(\x05\x12\x14\n\x0cweather_code\x18\x07 \x01(\x05\x12\x18\n\x10precipitation_cm\x18\x08 \x01(\x02\x12\x10\n\x08uv_index\x18\t \x01(\x02\x12\x1a\n\x12render_distance_km\x18\n \x01(\x02\x12\x16\n\x0e\x63loud_height_m\x18\x0b \x01(\x05\x12\x1b\n\x13\x63loud_cover_percent\x18\x0c \x01(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "weather_data_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_WEATHERDATAFULL"]._serialized_start = 37
    _globals["_WEATHERDATAFULL"]._serialized_end = 321
# @@protoc_insertion_point(module_scope)
